# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at: DB ==> Recette : 192.168.54.161
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://rec.cf.com:3306/toucan_dev_lot_2?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password: password
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: false
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
            hibernate.javax.cache.uri: ${spring.cache.jcache.config}
           # hibernate.cache.region.factory_class: com.campusfrance.op.config.jcache.SpringCacheRegionFactory
    cache:
        jcache:
            config: ehcache.xml
    mail:
        host: smtp.axones.fr
        port: 25
        username: msmaoui@axones.com
        password:
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false
liquibase:
    contexts: dev

server:
    port: 80
    compression:
      enabled: true
      mime-types: application/json

# ===================================================================
# OPApp specific properties
# ===================================================================

opapp:
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 16M
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    mail: # specific OPApp mail property, for standard properties see MailProperties
        from: no-reply@campusfrance.org
        baseUrl : https://toucan.campusfrance.org
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: op
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
    cas:
        casUrlLogin: https://rec.cf.com:10081/cas/login
        casUrlLogout: https://rec.cf.com:10081/cas/logout
        casUrlPrefix: https://rec.cf.com:10081/cas/
        casServiceUrl: http://localhost:80/login/cas
        casServiceHome: http://localhost:80/
        casGUCHome : http://192.168.54.162:8080/GCUtilisateur/guc/restapi/creationSimplifieeCompte

    upload:
        uploadBaseDirectory: Z:\\CDS\\CAMPUS FRANCE\\09 - Outil de Placement\\100-upload-dir
        uploadUserDirectory: \\users
        programBandeauDirectory: \\bandeau
        programLogoDirectory: \\logo
    payment:
        currency: EUR
        language: fr_FR
        pspId: CAMPUSFRANCE02TEST
        title: Paiement toucan
        keySign: Campusfr@nceEstNeEn2012!
        actionUrl: https://secure.ogone.com/ncol/test/orderstandard.asp
        #TODO: change for prod envirennment: actionUrl: https://secure.ogone.com/ncol/prod/orderstandard.asp
        homeUrl: http://localhost:80/
        acceptUrl: http://localhost:80/
        errorUrl: http://localhost:80/